<?php
include 'includes/db_config.php';
// $servername = "localhost";
// $username = "root"; // Replace with your MySQL username
// $password = ""; // Replace with your MySQL password
// $dbname = "majistic2k25";

// // Create a connection
// $conn = new mysqli($servername, $username, $password, $dbname);

// // Check connection
// if ($conn->connect_error) {
//     die("Connection failed: " . $conn->connect_error);
// }

// Get the JIS_ID from the URL
$jis_id = $_GET['jis_id'];

// Fetch the order details based on JIS_ID
$query = $conn->prepare("SELECT * FROM merchant_pay WHERE jis_id = ?");
$query->bind_param("s", $jis_id);
$query->execute();
$result = $query->get_result();
$order = $result->fetch_assoc();

if (!$order) {
    die("Order not found.");
}

// Razorpay API credentials
$keyId = "rzp_test_5y6HDO2HsDx5lK"; // Replace with your Razorpay Key ID
$keySecret = "sOQvnTPi8LdXe8JYYv0eGF2P"; // Replace with your Razorpay Key Secret

// Create an order using Razorpay API
$api_url = "https://api.razorpay.com/v1/orders";
$amount = $order['total_amount'] * 100; // Amount in paise (e.g., 50000 paise = 500 INR)
$currency = "INR";

$data = [
    'amount' => $amount,
    'currency' => $currency,
    'receipt' => $jis_id,
    'payment_capture' => 1 // Auto capture
];

$ch = curl_init($api_url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_USERPWD, $keyId . ':' . $keySecret);
curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($data));

$response = curl_exec($ch);
if (curl_errno($ch)) {
    die("Curl error: " . curl_error($ch));
}
curl_close($ch);

$orderResponse = json_decode($response);
if (json_last_error() !== JSON_ERROR_NONE) {
    die("Failed to parse JSON response.");
}

if (!isset($orderResponse->id)) {
    die("Failed to create Razorpay order.");
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payment - maJIStic 2k25</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center">Confirm Your Payment</h2>
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Order Details</h5>
                <p><strong>JIS ID:</strong> <?php echo htmlspecialchars($order['jis_id']); ?></p>
                <p><strong>Total Amount:</strong> ₹<?php echo htmlspecialchars($order['total_amount']); ?></p>
                <button id="pay-button" class="btn btn-success">Proceed to Pay</button>
            </div>
        </div>
    </div>

    <script>
        var options = {
            "key": "<?php echo htmlspecialchars($keyId); ?>", // Your Razorpay Key ID
            "amount": "<?php echo htmlspecialchars($orderResponse->amount); ?>", // Amount in paise
            "currency": "INR",
            "name": "maJIStic 2k25",
            "description": "Payment for Merchandise",
            "image": "https://example.com/your_logo.jpg", // Replace with your logo
            "order_id": "<?php echo htmlspecialchars($orderResponse->id); ?>", // Order ID generated by Razorpay
            "handler": function (response) {
                // Handle successful payment here
                alert("Payment successful! Payment ID: " + response.razorpay_payment_id);
                
                // Optionally, send payment details to your server for verification
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "update_payment_status.php", true);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.send("jis _id=<?php echo htmlspecialchars($jis_id); ?>&payment_id=" + response.razorpay_payment_id + "&amount_paid=" + <?php echo htmlspecialchars($orderResponse->amount); ?> + "&payment_date=" + new Date().toISOString());
            },
            "theme": {
                "color": "#F37254"
            }
        };

        document.getElementById('pay-button').onclick = function(e) {
            var rzp1 = new Razorpay(options);
            rzp1.open();
            e.preventDefault();
        }
    </script>
</body>
</html>